- hosts: primary
  name: Autoconverted job legacy-tempest-dsvm-networking-odl-multinode-carbon-snapshot
    from old job gate-tempest-dsvm-networking-odl-multinode-carbon-snapshot-nv
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          cat > clonemap.yaml << EOF
          clonemap:
            - name: openstack/devstack-gate
              dest: devstack-gate
          EOF
          /usr/zuul-env/bin/zuul-cloner -m clonemap.yaml --cache-dir /opt/git \
              https://opendev.org \
              openstack/devstack-gate
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          cat << 'EOF' >>"/tmp/dg-local.conf"
          [[local|localrc]]
          enable_plugin networking-odl https://opendev.org/openstack/networking-odl

          EOF
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PYTHONUNBUFFERED=true
          export DEVSTACK_GATE_NEUTRON=1
          export DEVSTACK_GATE_NEUTRON_DVR=1
          # Make sure tempest is installed, but run it out of the post_test_hooks.sh
          # script from the networking-odl repository.
          export DEVSTACK_GATE_TEMPEST=1
          export DEVSTACK_GATE_TEMPEST_NOTESTS=1

          export BRANCH_OVERRIDE=default
          if [ "$BRANCH_OVERRIDE" != "default" ] ; then
              export OVERRIDE_ZUUL_BRANCH=$BRANCH_OVERRIDE
          fi
          # Because we are testing a non standard project, add
          # our project repository. This makes zuul do the right
          # reference magic for testing changes.
          export PROJECTS="openstack/networking-odl $PROJECTS"

          # Keep localrc to be able to set some vars in pre_test_hook
          export KEEP_LOCALRC=1

          # specify ODL release to use
          export ODL_RELEASE_BASE=carbon-snapshot

          function pre_test_hook {
              if [ -f $BASE/new/networking-odl/devstack/pre_test_hook.sh ] ; then
                  . $BASE/new/networking-odl/devstack/pre_test_hook.sh
              fi
          }
          export -f pre_test_hook

          function post_test_hook {
              if [ -f $BASE/new/networking-odl/devstack/post_test_hook.sh ] ; then
                  . $BASE/new/networking-odl/devstack/post_test_hook.sh
              fi
          }
          export -f post_test_hook

          export DEVSTACK_GATE_TOPOLOGY="multinode"

          export DEVSTACK_GATE_SETTINGS=/opt/stack/new/networking-odl/devstack/devstackgaterc
          cp devstack-gate/devstack-vm-gate-wrap.sh ./safe-devstack-vm-gate-wrap.sh
          ./safe-devstack-vm-gate-wrap.sh
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
